name: Go

on: [ push, pull_request ]

jobs:
  build:
    name: create-fself
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Build windows version
      run: |
        mkdir build
        cd cmd/create-fself
        GOOS=windows go build -o ../../build/create-fself.exe -modfile=go-linux.mod

    - name: Build linux version
      run: |
        cd cmd/create-fself
        go build -o ../../build/create-fself -modfile=go-linux.mod
        
    - name: Build macOS version
      run: |
        cd cmd/create-fself
        GOOS=darwin go build -o ../../build/create-fself-macos -modfile=go-linux.mod

    - name: Create tarball
      run: tar -czvf binaries.tar.gz build/*
    
    - name: Upload windows version
      uses: actions/upload-artifact@v2
      with:
        name: create-fself.exe
        path: build/create-fself.exe

    - name: Upload linux version
      uses: actions/upload-artifact@v2
      with:
        name: create-fself
        path: build/create-fself

    - name: Upload macOS version
      uses: actions/upload-artifact@v2
      with:
        name: create-fself-macos
        path: build/create-fself-macos

    - name: Upload tarball
      uses: actions/upload-artifact@v2
      with:
        name: binaries.tar.gz
        path: binaries.tar.gz
